name: Building on self hosted runner

on:
  workflow_dispatch:
    {}

jobs:
  Build:
    name: Build  and post project
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Build
        id: build_step
        shell: bash
        run: |
          ~/Unity/Hub/Editor/2023.2.18f1/Editor/Unity                                                                 \
          -quit -batchmode -nographics                                                                                \
          -executeMethod Builder.Build                                                                                \
          -projectPath /home/connor/Documents/Runners/RelentlessAttackRunner/_work/RelentlessAttack/RelentlessAttack/ \
          -logfile /home/connor/Documents/Results/buildLog.txt

      - name: Post Log on Fail
        if: steps.build_step.outcome == 'failure'  # Only run if the test step failed
        uses: actions/upload-artifact@v4
        with:
          name: TestLogs
          path: /home/connor/Documents/Results/buildLog.txt

  publish-to-itch:
    name: Publish to Itch
    runs-on: self-hosted
    needs: Build
    steps:
    - name: Zip build
      shell: bash
      run: |
        zip -r /home/connor/Documents/ResultsWebGLBuild.zip /home/connor/Documents/Results/BuildOutput

    - name: Uploading to itch.io
      uses: KikimoraGames/itch-publish@v0.0.3
      with:
        butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
        gameData: /home/connor/Documents/ResultsWebGLBuild.zip
        itchUsername: connory97
        itchGameId: RelentlessAttack
        buildChannel: windows
