name: Build Action
on:
  push:
    branches:
      - 'main'

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2023.2.18f1
        targetPlatform:
          - WebGL
        projectName:
          - RelentlessAttack
        projectPath:
          - ./
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Caching
        uses: actions/cache@v3
        with:
          path: ./Library
          key: Library-${{matrix.projectName}}-${{matrix.targetPlatform}}
          restore-keys: |
            Library-
            Library-${{matrix.projectName}}-
            Library-${{matrix.projectName}}-${{matrix.targetPlatform}}

      - name: Unity Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Uploading the build
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

      - name: Test Artifact Upload
        run: ls -R

  publish-to-itch:
      name: Download Project
      runs-on: ubuntu-latest
      needs: build-project
      steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
            name: Build

      - name: Test Artifact Download
        run: ls -R
        
      - name: Uploading to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: RelentlessAttack
          ITCH_USER: ConnorY97
          PACKAGE: /home/runner/work/RelentlessAttack/RelentlessAttack/WebGL/WebGL
